version: "3"

services:
  mumble:
    image: ratopi/mumble:1.3.0-1
    build:
      context: .
    ports:
       - "64738:64738"
    volumes:
       - "mumble_conf:/conf/"
    restart: unless-stopped

volumes:
  mumble_conf:
    external:
      name: mumble_conf

